name: inputs-demo
on:
  workflow_dispatch:
    inputs:
      environment: 
        description: environment to deploy is dev
        required: true
        default: dev
jobs: 
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: deploy app at dev
        run: echo " deply app at ${{inputs.environment}}"
